/*
 * 389. Find the Difference
 * Easy
 * Topics
 * Companies
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Return the letter that was added to t.
 * 
 * 
 * 
 * Example 1:
 * 
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * Example 2:
 * 
 * Input: s = "", t = "y"
 * Output: "y"
 * 
 * 
 * Constraints:
 * 
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lowercase English letters.
 */




 class Solution {
    public char findTheDifference(String s, String t) {
        int[] freq = new int[26]; // Array to store frequency of characters
        
        // Count frequency of each character in s
        for (char c : s.toCharArray()) {
            freq[c - 'a']++;
        }
        
        // Find the character in t that has different frequency
        for (char c : t.toCharArray()) {
            if (freq[c - 'a']-- == 0) {
                return c;
            }
        }
        
        return ' ';
    }
}





/*
 * 
 * Approach 
 * 
 * 
 * 1. store the frequency of letters in string s 
 * 2. check for each word in given string t that it is present in string s by its frequency
 * 3. if any elements frequency found to be 0 then return that element
 * 4. otherwise return ' ' this condition will never occur.
 */